From: A.K.

# Basics of Linear Algebra

1. Defining a vector in Python

2. The norm of vectors

3. Calculating metrics (Euclidean, Manhattan, etc.)

4. Scalar product of vectors

5. Defining a matrix in Python

6. Operations on matrices

7. Finding a matrix determinant

8. Defining a system of linear equations in Python

9. Finding an inverse matrix

10. Singular decomposition of matrices

In [1]:
import numpy as np

## 1. Defining a vector in Python


A vector (one-dimensional array) can be specified using the ***linspace*** function

In [2]:
vectorA = np.linspace(-2, 2, 17)

vectorA

array([-2.  , -1.75, -1.5 , -1.25, -1.  , -0.75, -0.5 , -0.25,  0.  ,
        0.25,  0.5 ,  0.75,  1.  ,  1.25,  1.5 ,  1.75,  2.  ])

*You can also set the vector directly*

In [3]:
vectorB = np.array([-2.5, 1.5, 0.3, -4.2, 0.25, -0.15, 3.4, 5.3, 0.3, 5.4, -3.2, -1.3, 2.5, 1, -2, 0.8, -1.5], float);

vectorB

array([-2.5 ,  1.5 ,  0.3 , -4.2 ,  0.25, -0.15,  3.4 ,  5.3 ,  0.3 ,
        5.4 , -3.2 , -1.3 ,  2.5 ,  1.  , -2.  ,  0.8 , -1.5 ])

## 2&4. The norm and Scalar product of vectors


*Euclidean norm of the vector* ***A***

In [4]:
round(np.linalg.norm(vectorA), 2)

5.05

*Euclidean norm of the vector* ***B***

In [5]:
round(np.linalg.norm(vectorB), 2)

11.01

*Manhattan norm of the vector* ***A***

In [6]:
round(np.linalg.norm(vectorA, ord = 1), 2)

18.0

*Manhattan norm of the vector* ***B***

In [7]:
round(np.linalg.norm(vectorB, ord = 1), 2)

35.6

*Scalar product of vectors* ***A*** *and* ***B***

In [8]:
round(np.dot(vectorA, vectorB), 2)

1.94

## 3. Calculating metrics (Euclidean, Manhattan, etc.)


*Manhattan Metric*

In [9]:
round(np.linalg.norm(vectorA - vectorB, ord = 1), 2)

40.7

*Euclidean metric*

In [10]:
round(np.linalg.norm(vectorA - vectorB), 2)

11.95

*Other metrics*

In [11]:
round(np.linalg.norm(vectorA - vectorB, ord = np.inf), 2)

5.55

In [12]:
round(np.linalg.norm(vectorA - vectorB, ord = -np.inf), 2)

0.25

In [13]:
round(np.linalg.norm(vectorA - vectorB, ord = 0), 2)

17.0

In [49]:
vector = np.array([3, 1, 5])
vector2 = np.array([2, 1, 1])

# Minkowski norm

def minkowski(a, b, p=2):
    assert len(a) == len(b), "'a' and 'b' must be of the same length"
    return pow(sum((abs(x-y)**p) for x,y in zip(a,b)), 1/p)
print('The Minkowski norm for two vectors:', minkowski(vector, vector2))

The Minkowski norm for two vectors: 4.123105625617661


In [50]:
# Levenshtein distance
def distance(a, b):
    n, m = len(a), len(b)
    if n > m:
        a, b = b, a
        n, m = m, n

    current_row = range(n + 1)
    for i in range(1, m + 1):
        previous_row, current_row = current_row, [i] + [0] * n
        for j in range(1, n + 1):
            add, delete, change = previous_row[j] + 1, current_row[j - 1] + 1, previous_row[j - 1]
            if a[j - 1] != b[i - 1]:
                change += 1
            current_row[j] = min(add, delete, change)

    return current_row[n]

print('Levenstein distance for two vectors:', distance(vector, vector2))

Levenstein distance for two vectors: 2


## 5. Defining a matrix in Python

*A matrix (two-dimensional array) can be created as follows:*

In [14]:
matrixA = np.matrix([[-2, 5, 3], [-1, 3, 4],[-7, 2, 1]])

matrixA

matrix([[-2,  5,  3],
        [-1,  3,  4],
        [-7,  2,  1]])

*You can also do this*

In [15]:
matrixB = np.matrix('7 2 3; -3 5 7; -1 2 5')

matrixB

matrix([[ 7,  2,  3],
        [-3,  5,  7],
        [-1,  2,  5]])

In [16]:
matrixC = np.matrix('3 2 3; 2 5 4')

matrixC

matrix([[3, 2, 3],
        [2, 5, 4]])

## 6. Operations on matrices

*Matrix Addition*

In [17]:
matrixA + matrixB

matrix([[ 5,  7,  6],
        [-4,  8, 11],
        [-8,  4,  6]])

*Subtraction of Matrices*

In [18]:
matrixA - matrixB

matrix([[-9,  3,  0],
        [ 2, -2, -3],
        [-6,  0, -4]])

In [19]:
matrixB - matrixA

matrix([[ 9, -3,  0],
        [-2,  2,  3],
        [ 6,  0,  4]])

*Multiplication of a matrix by a number*

In [20]:
matrixA * 4

matrix([[ -8,  20,  12],
        [ -4,  12,  16],
        [-28,   8,   4]])

In [21]:
matrixB * 0

matrix([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])

In [22]:
matrixC * -2

matrix([[ -6,  -4,  -6],
        [ -4, -10,  -8]])

In [23]:
matrixB * 5

matrix([[ 35,  10,  15],
        [-15,  25,  35],
        [ -5,  10,  25]])

*Multiplication of matrices by each other*

In [24]:
matrixC.dot(matrixB)

matrix([[12, 22, 38],
        [-5, 37, 61]])

In [25]:
np.dot(matrixA, matrixB)

matrix([[-32,  27,  44],
        [-20,  21,  38],
        [-56,  -2,  -2]])

In [26]:
np.dot(matrixC, matrixA)

matrix([[-29,  27,  20],
        [-37,  33,  30]])

*Dividing a matrix by a number*

In [27]:
matrixA / -2

matrix([[ 1. , -2.5, -1.5],
        [ 0.5, -1.5, -2. ],
        [ 3.5, -1. , -0.5]])

In [28]:
matrixB / 4

matrix([[ 1.75,  0.5 ,  0.75],
        [-0.75,  1.25,  1.75],
        [-0.25,  0.5 ,  1.25]])

In [29]:
matrixC / -0.25

matrix([[-12.,  -8., -12.],
        [ -8., -20., -16.]])

*Transpose of a matrix*

In [30]:
matrixA.transpose()

matrix([[-2, -1, -7],
        [ 5,  3,  2],
        [ 3,  4,  1]])

In [31]:
matrixB.transpose()

matrix([[ 7, -3, -1],
        [ 2,  5,  2],
        [ 3,  7,  5]])

In [32]:
matrixC.transpose()

matrix([[3, 2],
        [2, 5],
        [3, 4]])

*The matrix rank is calculated using the function* ***matrix_rank***

In [33]:
np.linalg.matrix_rank(matrixA)

3

In [34]:
np.linalg.matrix_rank(matrixB)

3

In [35]:
np.linalg.matrix_rank(matrixC)

2

## 7. Finding a matrix determinant

*The matrix determinant is found using the function* ***det***

In [36]:
round(np.linalg.det(matrixA), 2)

-68.0

In [37]:
round(np.linalg.det(matrixB), 2)

90.0

In [51]:
# another example

matrix1 = np.array([
    [1, 2],
    [4, 5]
])

matrix2 = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

matrix3 = np.array([
    [1, 2, 3, 7, 4, 9, 5],
    [2, 5, 6, 1, 3, 8, 3],
    [4, 0, 5, 7, 4, 4, 1],
    [5, 5, 1, 8, 7, 3, 2],
    [4, 4, 6, 7, 4, 2, 1],
    [1, 5, 7, 0, 6, 9, 7],
    [7, 8, 4, 9, 4, 1, 4]
])

print("Finding a determinant using a library")
mat1 = np.linalg.det(matrix1)
mat2 = np.linalg.det(matrix2)
mat3 = np.linalg.det(matrix3)
print(mat1)
print(mat2)
print(mat3)

print("Finding a determinant without a library")
def getMatDet2x2(mat):
     return mat[0, 0] * mat[1, 1] - mat[0, 1] * mat[1, 0]
print(getMatDet2x2(matrix1))

import copy
        
def minor( A, i, j ):
    M = copy.deepcopy(A) 
    del M[i]
    for i in range(len(A[0]) - 1):
        del M[i][j]
    return M   
    
def det( A ):
    m = len(A)
    n = len(A[0])
    if m != n:
        return None
    if n == 1:
        return A[0][0]
    signum = 1
    determinant = 0
    # decomposition on the first line
    for j in range( n ):
        determinant += A[0][j]*signum*det(minor(A, 0, j)) 
        signum *= -1
    return determinant                           
      
A =[[1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]]
B =[[1, 2, 3, 7, 4, 9, 5],
    [2, 5, 6, 1, 3, 8, 3],
    [4, 0, 5, 7, 4, 4, 1],
    [5, 5, 1, 8, 7, 3, 2],
    [4, 4, 6, 7, 4, 2, 1],
    [1, 5, 7, 0, 6, 9, 7],
    [7, 8, 4, 9, 4, 1, 4]]
print(det(A))
print(det(B))

Finding a determinant using a library
-2.9999999999999996
0.0
-189715.99999999985
Finding a determinant without a library
-3
0
-189716


## 8. Defining a system of linear equations in Python

 ***#1***

In [38]:
L1 = np.array([[1, 1, 1], [8, 4, 6], [15, 3, 5]]) #left part
R1 = np.array([0, 8, 0]) #right part

np.linalg.solve(L1, R1)

array([-1., -5.,  6.])

***#2***

In [39]:
L2 = np.array([[2, 5, 4, 1], [1, 3, 2, 1], [2, 10, 9, 7], [3, 8, 9, 2]])
R2 = np.array([20, 11, 40, 37])

np.linalg.solve(L2, R2)

array([ 1.00000000e+00,  2.00000000e+00,  2.00000000e+00, -3.70074342e-15])

## 9. Finding an inverse matrix

*Initial matrix* ***A***

In [40]:
matrixA

matrix([[-2,  5,  3],
        [-1,  3,  4],
        [-7,  2,  1]])

*Inverse matrix* ***A***

In [41]:
matrixA_inv = np.linalg.inv(matrixA)

matrixA_inv.round(3)

array([[ 0.074, -0.015, -0.162],
       [ 0.397, -0.279, -0.074],
       [-0.279,  0.456,  0.015]])

*Inverse matrix from inverse matrix* ***A*** *( checking)*

In [42]:
np.linalg.inv(matrixA_inv)

matrix([[-2.,  5.,  3.],
        [-1.,  3.,  4.],
        [-7.,  2.,  1.]])

*Inverse matrix* ***B***

In [43]:
np.linalg.inv(matrixB).round(3)

array([[ 0.122, -0.044, -0.011],
       [ 0.089,  0.422, -0.644],
       [-0.011, -0.178,  0.456]])

## 10. Singular decomposition of matrices

*Singular decomposition is performed using the method* ***svd***

*Singular matrix decomposition for* ***A***

In [44]:
U1, D1, V1 = np.linalg.svd(matrixA)
print("U1")
print(U1.round(3))
print("\n")

print("D1")
print(D1.round(3))
print("\n")

print("V1")
print(V1.round(3))

U1
[[-0.598 -0.438 -0.671]
 [-0.449 -0.511  0.733]
 [-0.664  0.74   0.109]]


D1
[9.475 5.124 1.401]


V1
[[ 0.664 -0.598 -0.449]
 [-0.74  -0.438 -0.511]
 [-0.109 -0.671  0.733]]


*Back reconstruction into the matrix* ***A***

In [45]:
np.linalg.inv(np.transpose(V1).dot(np.diag(1/D1).dot(np.transpose(U1)))).round(2)

array([[-2.,  5.,  3.],
       [-1.,  3.,  4.],
       [-7.,  2.,  1.]])

*Singular matrix decomposition for* ***B***

In [46]:
U2, D2, V2 = np.linalg.svd(matrixB)

print("U2")
print(U2.round(3))
print("\n")

print("D2")
print(D2.round(3))
print("\n")

print("V2")
print(V2.round(3))

U2
[[-0.267  0.96  -0.089]
 [-0.824 -0.275 -0.496]
 [-0.5   -0.059  0.864]]


D2
[10.742  7.642  1.096]


V2
[[ 0.103 -0.526 -0.844]
 [ 0.995  0.056  0.086]
 [ 0.002 -0.849  0.529]]


*Back reconstruction into the matrix* ***B***

In [47]:
np.linalg.inv(np.transpose(V2).dot(np.diag(1/D2)).dot(np.transpose(U2))).round(2)

array([[ 7.,  2.,  3.],
       [-3.,  5.,  7.],
       [-1.,  2.,  5.]])